# Generated by Django 3.1 on 2021-05-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Genero', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=50, verbose_name='Genero')),
            ],
        ),
    ]
